### PR TITLE
Safer loading

### PR DESCRIPTION
**Pull request by chriselrod**
@tkf @fredrikekre
Is this better? Or should I take an approach like JuliaLang/julia/pull/43270?
Also, I'm not sure how to test if this actually works.
The current tests were passing even in the broken versions.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Seems fine. The main concern should be whether Hwloc is available though.

**Comment by chriselrod** [comment]
> Seems fine. The main concern should be whether Hwloc is available though.

Why may it not be?
It's part of CPUSummary's project, so `Base.lower_path_setup_code()` should make it available, if the project's been instantiated?

Of course something seems to be going wrong, so it's probable that I am mistaken somewhere.

**Comment by chriselrod** [comment]
> But you are only allowed to load "top level packages", and if `Hwloc` hasn't been explicitly `Pkg.add`ed by the user it will fail.

Ah.
CPUSummary.jl is itself allowed to `using Hwloc`.
One should thus be allowed to `using Hwloc` when using the CPUSummary.jl project.

I guess `Base.load_path_setup_code()` creates setup code for the main project, and not from the scope/environment it is called from?

**Comment by fredrikekre** [comment]
This works:
```julia
julia> Hwloc = Base.require(Base.PkgId(Base.UUID("0e44f5e4-bd66-52a0-8798-143a42290a1d"), "Hwloc"))
Hwloc
```

**Pull request merged**
